import { chromium } from 'playwright';
const B='http://localhost:20128';
const b=await chromium.launch(); const p=await b.newPage();
await p.goto(B+'/login'); await p.waitForSelector('input[type=password]',{timeout:20000});
await p.fill('input[type=password]','e2e-test-pass'); await p.keyboard.press('Enter'); await p.waitForURL('**/home',{timeout:20000});
const post=(u,d)=>p.evaluate(async([u,d])=>{const r=await fetch(u,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});return {s:r.status,j:await r.json().catch(()=>null)}},[u,d]);
const key=process.env.LLM_API_KEY, base=(process.env.LLM_BASE_URL||'').replace(/\/v1$/,'');
console.log('base',base,'key?',!!key);
const node=await post('/api/provider-nodes',{kind:'openai-compatible-chat',name:'OmniRoute GW',data:{baseUrl:base}});
console.log('node',JSON.stringify(node).slice(0,300));
const pid=node.j?.node?.id;
const conn=await post('/api/provider-connections',{provider:pid,name:'gw1',data:{apiKey:key}});
console.log('conn',JSON.stringify(conn).slice(0,300));
const cid=conn.j?.connection?.id;
const exp=await post('/api/credentials/expiration',{connectionId:cid,expiresAt:new Date(Date.now()+3*864e5).toISOString(),warnDays:7});
console.log('exp',JSON.stringify(exp).slice(0,300));
const sync=await post('/api/synced-available-models',{});
console.log('sync',JSON.stringify(sync).slice(0,500));
await b.close();
