namespace LLMRouter.Core.Registry;

/// <summary>Port of upstream open-sse/config/freeModelCatalog.data.ts (hand-curated). Re-sync on upstream changes.</summary>
public static class FreeModelCatalog
{
    public const string CuratedAt = "2026-09-12";
    public sealed record FreeModelBudget(string Provider, string ModelId, string DisplayName, long MonthlyTokens, long CreditTokens, string FreeType, string PoolKey, string Tos);
    public static readonly FreeModelBudget[] Budgets =
    [
        new("agentrouter","claude-opus-4-8","Claude Opus 4.8",0,200000000,"one-time-initial","agentrouter","caution"),
        new("agentrouter","claude-opus-5","Claude Opus 5",0,200000000,"one-time-initial","agentrouter","caution"),
        new("agentrouter","gpt-5.6-sol","GPT-5.6 Sol",0,200000000,"one-time-initial","agentrouter","caution"),
        new("agy","gemini-3.7-flash-high","Gemini 3.7 Flash (High)",0,0,"keyless","agy","avoid"),
        new("agy","gemini-3.7-flash-medium","Gemini 3.7 Flash (Medium)",0,0,"keyless","agy","avoid"),
        new("agy","gemini-3.7-flash-low","Gemini 3.7 Flash (Low)",0,0,"keyless","agy","avoid"),
        new("agy","gemini-pro-agent","Gemini 3.1 Pro (High)",0,0,"keyless","agy","avoid"),
        new("agy","gemini-3.1-pro-low","Gemini 3.1 Pro (Low)",0,0,"keyless","agy","avoid"),
        new("agy","gemini-3.1-flash-lite","Gemini 3.1 Flash Lite",0,0,"keyless","agy","avoid"),
        new("agy","claude-opus-4-6-thinking","Claude Opus 4.6 (Thinking)",0,0,"keyless","agy","avoid"),
        new("agy","claude-sonnet-4-6","Claude Sonnet 4.6 (Thinking)",0,0,"keyless","agy","avoid"),
        new("agy","gpt-oss-120b-medium","GPT-OSS 120B (Medium)",0,0,"keyless","agy","avoid"),
        new("ai21","jamba-large-1.7","jamba-large-1.7",0,10000000,"one-time-initial","ai21","avoid"),
        new("ai21","jamba-mini-2","jamba-mini-2",0,10000000,"one-time-initial","ai21","avoid"),
        new("api-airforce","x-ai/grok-3","Grok-3 (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","x-ai/grok-2-1212","Grok-2 1212 (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","anthropic/claude-3.7-sonnet","Claude 3.7 Sonnet (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","qwen/qwen3-32b","Qwen3 32B (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","moonshot/kimi-k2.6","Kimi K2.6 (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","google/gemini-2.5-flash","Gemini 2.5 Flash (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("api-airforce","deepseek/deepseek-v3","DeepSeek V3 (Free)",24000000,0,"recurring-daily","api-airforce","caution"),
        new("arcee-ai","arcee-ai/trinity-large-preview:free","Arcee Trinity Large Preview (free)",4800000,0,"recurring-daily","arcee-free","caution"),
        new("baichuan","Baichuan4","Baichuan 4",0,0,"one-time-initial","baichuan","ambiguous"),
        new("baidu","ernie-4.0-8k","ERNIE 4.0 8K",0,0,"recurring-uncapped","baidu","caution"),
        new("bazaarlink","auto:free","Auto Free (Zero Cost)",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","claude-opus-4.7","Claude Opus 4.7",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","claude-sonnet-4.6","Claude Sonnet 4.6",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","claude-haiku-4.5","Claude Haiku 4.5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gpt-5.5","GPT-5.5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gpt-5.4","GPT-5.4",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gpt-5.4-mini","GPT-5.4 Mini",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gpt-5.4-nano","GPT-5.4 Nano",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","grok-4.3","Grok 4.3",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","grok-4.20","Grok 4.20",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gemini-3.1-pro-preview","Gemini 3.1 Pro",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gemini-3-flash-preview","Gemini 3 Flash",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gemini-3.1-flash-lite-preview","Gemini 3.1 Flash Lite",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gemma-4-31b-it","Gemma 4 31B",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","gemma-4-26b-a4b-it","Gemma 4 26B A4B",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","deepseek-v3.2","DeepSeek V3.2",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","kimi-k2.6","Kimi K2.6",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","kimi-k2.5","Kimi K2.5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","glm-5.1","GLM 5.1",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","glm-5","GLM 5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","mimo-v2.5-pro","MiMo-V2.5-Pro",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","mimo-v2.5","MiMo-V2.5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","minimax-m2.7","MiniMax M2.7",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","minimax-m2.5","MiniMax M2.5",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","llama-4-maverick","Llama 4 Maverick",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","llama-4-scout","Llama 4 Scout",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","llama-3.3-70b-instruct","Llama 3.3 70B",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","qwen3.6-plus","Qwen 3.6 Plus",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","mistral-large-2512","Mistral Large 3",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","mistral-medium-3.1","Mistral Medium 3.1",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","mistral-small-2603","Mistral Small 4",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("bazaarlink","nemotron-3-super-120b-a12b","Nemotron 3 Super",3600000,0,"recurring-daily","bazaarlink","caution"),
        new("blackbox","gpt-4o","GPT-4o",0,0,"keyless","blackbox","avoid"),
        new("blackbox","gemini-2.5-flash","Gemini 2.5 Flash",0,0,"keyless","blackbox","avoid"),
        new("blackbox","claude-sonnet-4","Claude Sonnet 4",0,0,"keyless","blackbox","avoid"),
        new("blackbox","deepseek-v3","DeepSeek V3",0,0,"keyless","blackbox","avoid"),
        new("blackbox","blackboxai","Blackbox AI",0,0,"keyless","blackbox","avoid"),
        new("blackbox","blackboxai-pro","Blackbox AI Pro",0,0,"keyless","blackbox","avoid"),
        new("bluesminds","gpt-4o","GPT-4o",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gpt-4o-mini","GPT-4o Mini",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gpt-4.1","GPT-4.1",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gpt-4.1-mini","GPT-4.1 Mini",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gpt-4.1-nano","GPT-4.1 Nano",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","claude-sonnet-4-5","Claude Sonnet 4.5",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","claude-haiku-4-5","Claude Haiku 4.5",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gemini-2.0-flash","Gemini 2.0 Flash",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gemini-2.0-flash-exp","Gemini 2.0 Flash (Exp)",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","deepseek-reasoner","DeepSeek Reasoner",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","deepseek-chat","DeepSeek Chat",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","qwen-plus","Qwen Plus",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","qwen-turbo","Qwen Turbo",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","kimi-k2","Kimi K2",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","kimi-k2-thinking","Kimi K2 Thinking",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","glm-4.7","GLM 4.7",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","glm-4-flash","GLM 4 Flash",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","minimax-m2.5","MiniMax M2.5",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","claude-opus-4-5","Claude Opus 4.5 (VIP)",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","gemini-2.5-pro","Gemini 2.5 Pro (VIP)",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","grok-3","Grok-3 (VIP)",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bluesminds","qwen-max","Qwen Max (VIP)",7200000,0,"recurring-daily","bluesminds","ambiguous"),
        new("bytez","meta-llama/Llama-3.3-70B-Instruct","meta-llama/Llama-3.3-70B-Instruct",0,1000000,"recurring-credit","bytez","ambiguous"),
        new("bytez","mistralai/Mistral-7B-Instruct-v0.3","mistralai/Mistral-7B-Instruct-v0.3",0,1000000,"recurring-credit","bytez","ambiguous"),
        new("bytez","Qwen/Qwen2.5-72B-Instruct","Qwen/Qwen2.5-72B-Instruct",0,1000000,"recurring-credit","bytez","ambiguous"),
        new("cerebras","zai-glm-4.7","GLM 4.7",0,0,"one-time-initial","cerebras","caution"),
        new("cerebras","gpt-oss-120b","GPT OSS 120B",0,0,"one-time-initial","cerebras","caution"),
        new("cloudflare-ai","@cf/mistral/mistral-7b-instruct-v0.2-lora","Mistral 7B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/qwen/qwen2.5-coder-32b-instruct","Qwen 2.5 Coder 32B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/deepseek-ai/deepseek-r1-distill-qwen-32b","DeepSeek R1 Distill 32B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/meta/llama-3.3-70b-instruct-fp8-fast","Llama 3.3 70B (FP8 Fast 🆓 ~150 resp/day)",30000000,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/meta/llama-3.2-3b-instruct","Llama 3.2 3B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/qwen/qwq-32b","QwQ 32B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/zai-org/glm-4.7-flash","GLM 4.7 Flash (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/moonshotai/kimi-k2.6","Kimi K2.6 (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cloudflare-ai","@cf/google/gemma-4-26b-a4b-it","Gemma 4 26B (🆓)",0,0,"recurring-daily","cloudflare-ai","caution"),
        new("cohere","command-a-reasoning-08-2025","Command A Reasoning (Aug 2025)",800000,0,"recurring-monthly","cohere","caution"),
        new("cohere","command-a-vision-07-2025","Command A Vision (Jul 2025)",800000,0,"recurring-monthly","cohere","caution"),
        new("cohere","command-a-03-2025","Command A (Mar 2025)",800000,0,"recurring-monthly","cohere","caution"),
        new("cohere","command-r7b-12-2024","Command R7B (Dec 2024)",800000,0,"recurring-monthly","cohere","caution"),
        new("cohere","command-r-plus-08-2024","Command R Plus (Aug 2024)",800000,0,"recurring-monthly","cohere","caution"),
        new("cohere","command-r-08-2024","Command R (Aug 2024)",800000,0,"recurring-monthly","cohere","caution"),
        new("coze","claude-3-7-sonnet-20250514","Claude 3.7 Sonnet",0,0,"recurring-daily","coze","avoid"),
        new("deepinfra","anthropic/claude-4-opus","anthropic/claude-4-opus",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","anthropic/claude-4-sonnet","anthropic/claude-4-sonnet",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","openai/gpt-oss-120b","openai/gpt-oss-120b",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","openai/gpt-oss-20b","openai/gpt-oss-20b",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","google/gemma-4-31B-it","google/gemma-4-31B-it",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","google/gemma-4-26B-A4B-it","google/gemma-4-26B-A4B-it",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","nvidia/NVIDIA-Nemotron-3-Super-120B-A12B","nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning","nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8","meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","meta-llama/Llama-4-Scout-17B-16E-Instruct","meta-llama/Llama-4-Scout-17B-16E-Instruct",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","meta-llama/Llama-3.3-70B-Instruct-Turbo","meta-llama/Llama-3.3-70B-Instruct-Turbo",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","NousResearch/Hermes-3-Llama-3.1-405B","NousResearch/Hermes-3-Llama-3.1-405B",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","deepseek-ai/DeepSeek-V4-Pro","deepseek-ai/DeepSeek-V4-Pro",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","deepseek-ai/DeepSeek-V4-Flash","deepseek-ai/DeepSeek-V4-Flash",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","zai-org/GLM-5.1","zai-org/GLM-5.1",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","moonshotai/Kimi-K2.6","moonshotai/Kimi-K2.6",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","MiniMaxAI/MiniMax-M2.5","MiniMaxAI/MiniMax-M2.5",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","Qwen/Qwen3.6-35B-A3B","Qwen/Qwen3.6-35B-A3B",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","Qwen/Qwen3.5-397B-A17B","Qwen/Qwen3.5-397B-A17B",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","Qwen/Qwen3.5-122B-A10B","Qwen/Qwen3.5-122B-A10B",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","XiaomiMiMo/MiMo-V2.5-Pro","XiaomiMiMo/MiMo-V2.5-Pro",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepinfra","XiaomiMiMo/MiMo-V2.5","XiaomiMiMo/MiMo-V2.5",0,1000000,"one-time-initial","deepinfra","caution"),
        new("deepseek","deepseek-v4-pro","DeepSeek V4 Pro",0,5000000,"one-time-initial","deepseek","ok"),
        new("deepseek","deepseek-v4-flash","DeepSeek V4 Flash",0,5000000,"one-time-initial","deepseek","ok"),
        new("doubao","doubao-pro-32k","Doubao Pro 32K",0,15000000,"one-time-initial","doubao","ambiguous"),
        new("duckduckgo-web","gpt-5.4-mini","GPT-5.4 Mini",0,0,"keyless","duckduckgo-web","avoid"),
        new("duckduckgo-web","gpt-5.6-luna","GPT-5.6 Luna",0,0,"keyless","duckduckgo-web","avoid"),
        new("duckduckgo-web","claude-haiku-4-5","Claude Haiku 4.5",0,0,"keyless","duckduckgo-web","avoid"),
        new("duckduckgo-web","mistral-small-2603","Mistral Small 4",0,0,"keyless","duckduckgo-web","avoid"),
        new("duckduckgo-web","tinfoil/gpt-oss-120b","gpt-oss 120B",0,0,"keyless","duckduckgo-web","avoid"),
        new("duckduckgo-web","tinfoil/gemma4-31b","Gemma 4 31B",0,0,"keyless","duckduckgo-web","avoid"),
        new("fireworks","deepseek-v4-flash","DeepSeek V4 Flash",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","deepseek-v4-pro","DeepSeek V4 Pro",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","glm-5p1","GLM 5.1",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","gpt-oss-120b","OpenAI gpt-oss-120b",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","gpt-oss-20b","OpenAI gpt-oss-20b",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","kimi-k2p5","Kimi K2.5",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","kimi-k2p6","Kimi K2.6",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","minimax-m2p5","MiniMax M2.5",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","minimax-m2p7","MiniMax M2.7",0,1000000,"one-time-initial","fireworks","avoid"),
        new("fireworks","qwen3p6-plus","Qwen3.6 Plus",0,1000000,"one-time-initial","fireworks","avoid"),
        new("freemodel-dev","gpt-5.5","GPT-5.5",0,0,"one-time-initial","freemodel-dev","unknown"),
        new("freemodel-dev","gpt-5.4","GPT-5.4",0,0,"one-time-initial","freemodel-dev","unknown"),
        new("freemodel-dev","gpt-5.4-mini","GPT-5.4 Mini",0,0,"one-time-initial","freemodel-dev","unknown"),
        new("freemodel-dev","gpt-5.3-codex","GPT-5.3 Codex",0,0,"one-time-initial","freemodel-dev","unknown"),
        new("friendliai","meta-llama-3.1-70b-instruct","meta-llama-3.1-70b-instruct",0,0,"keyless","friendliai","avoid"),
        new("friendliai","meta-llama-3.1-8b-instruct","meta-llama-3.1-8b-instruct",0,0,"keyless","friendliai","avoid"),
        new("gemini","gemini-2.5-flash","Gemini 2.5 Flash",0,0,"recurring-uncapped","gemini-free","caution"),
        new("gemini","gemini-2.5-flash-lite","Gemini 2.5 Flash-Lite",0,0,"recurring-uncapped","gemini-free","caution"),
        new("gemini","gemini-3-flash-preview","Gemini 3 Flash Preview",0,0,"recurring-uncapped","gemini-free","caution"),
        new("gemini","gemini-3.1-flash-lite","Gemini 3.1 Flash-Lite",0,0,"recurring-uncapped","gemini-free","caution"),
        new("glm-cn","glm-4-flash","GLM-4-Flash",0,0,"recurring-uncapped","zhipu-flash-free","ok"),
        new("glm-cn","glm-4.5-flash","GLM-4.5-Flash",0,0,"recurring-uncapped","zhipu-flash-free","ok"),
        new("glm-cn","glm-4.7-flash","GLM-4.7-Flash",0,0,"recurring-uncapped","zhipu-flash-free","ok"),
        new("glm-cn","glm-signup-bonus","Z.AI — 20M signup bonus",0,20000000,"one-time-initial","zhipu-signup","ok"),
        new("huggingchat","baidu/ERNIE-4.5-VL-424B-A47B-Base-PT","ERNIE 4.5 VL 424B A47B Base PT",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","CohereLabs/c4ai-command-r7b-12-2024","Command R7B 12-2024",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","CohereLabs/command-a-reasoning-08-2025","Command A Reasoning 08-2025",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","CohereLabs/command-a-vision-07-2025","Command A Vision 07-2025",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","deepseek-ai/DeepSeek-V4-Pro","DeepSeek V4 Pro",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","deepseek-ai/DeepSeek-V4-Flash","DeepSeek V4 Flash",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","google/gemma-4-31B-it","Gemma 4 31B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","google/gemma-4-26B-A4B-it","Gemma 4 26B A4B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","inclusionAI/Ling-2.6-1T","Ling 2.6 1T",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","meta-llama/Llama-4-Scout-17B-16E-Instruct","Llama 4 Scout 17B 16E Instruct",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8","Llama 4 Maverick 17B 128E Instruct FP8",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","MiniMaxAI/MiniMax-M3","MiniMax M3",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","moonshotai/Kimi-K2.7-Code","Kimi K2.7 Code",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","moonshotai/Kimi-K2.6","Kimi K2.6",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B-NVFP4","NVIDIA Nemotron 3 Ultra 550B A55B NVFP4",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","openai/gpt-oss-120b","GPT-OSS 120B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","openai/gpt-oss-20b","GPT-OSS 20B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","Qwen/Qwen3.5-122B-A10B","Qwen3.5 122B A10B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","Qwen/Qwen3.5-397B-A17B","Qwen3.5 397B A17B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","Qwen/Qwen3.6-27B","Qwen3.6 27B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","Qwen/Qwen3.6-35B-A3B","Qwen3.6 35B A3B",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","stepfun-ai/Step-3.7-Flash","Step 3.7 Flash",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","XiaomiMiMo/MiMo-V2.5-Pro","MiMo V2.5 Pro",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingchat","zai-org/GLM-5.2","GLM 5.2",500000,0,"recurring-monthly","huggingchat","caution"),
        new("huggingface","meta-llama/llama-3.1-8b-instruct","Llama 3.1 8B",200000,0,"recurring-monthly","huggingface","caution"),
        new("huggingface","meta-llama/llama-3.2-11b-instruct","Llama 3.2 11B",200000,0,"recurring-monthly","huggingface","caution"),
        new("huggingface","mistralai/mistral-7b-instruct","Mistral 7B",200000,0,"recurring-monthly","huggingface","caution"),
        new("huggingface","google/gemma-2-9b-it","Gemma 2 9B",200000,0,"recurring-monthly","huggingface","caution"),
        new("huggingface","Qwen/Qwen2.5-7B-Instruct","Qwen 2.5 7B",200000,0,"recurring-monthly","huggingface","caution"),
        new("huggingface","deepseek-ai/DeepSeek-V3","DeepSeek V3",200000,0,"recurring-monthly","huggingface","caution"),
        new("hyperbolic","Qwen/QwQ-32B","QwQ 32B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","deepseek-ai/DeepSeek-R1","DeepSeek R1",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","deepseek-ai/DeepSeek-V3","DeepSeek V3",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","meta-llama/Llama-3.3-70B-Instruct","Llama 3.3 70B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","meta-llama/Llama-3.2-3B-Instruct","Llama 3.2 3B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","Qwen/Qwen2.5-72B-Instruct","Qwen 2.5 72B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","Qwen/Qwen2.5-Coder-32B-Instruct","Qwen 2.5 Coder 32B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("hyperbolic","NousResearch/Hermes-3-Llama-3.1-70B","Hermes 3 70B",0,5000000,"one-time-initial","hyperbolic","ok"),
        new("iflytek","generalv3.5","General V3.5",0,0,"keyless","iflytek","avoid"),
        new("inference-net","meta-llama/Llama-3.3-70B-Instruct","meta-llama/Llama-3.3-70B-Instruct",0,0,"recurring-monthly","inference-net","caution"),
        new("inference-net","deepseek-ai/DeepSeek-R1","deepseek-ai/DeepSeek-R1",0,0,"recurring-monthly","inference-net","caution"),
        new("inference-net","Qwen/Qwen2.5-72B-Instruct","Qwen/Qwen2.5-72B-Instruct",0,0,"recurring-monthly","inference-net","caution"),
        new("kiro","claude-sonnet-4.5","Claude Sonnet 4.5",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","claude-haiku-4.5","Claude Haiku 4.5",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","deepseek-3.2","DeepSeek V3.2",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","minimax-m2.5","MiniMax M2.5",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","minimax-m2.1","MiniMax M2.1",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","glm-5","GLM-5",25000,0,"recurring-monthly","kiro","avoid"),
        new("kiro","qwen3-coder-next","Qwen3 Coder Next",25000,0,"recurring-monthly","kiro","avoid"),
        new("liquid","liquid-lfm-40b","Liquid LFM 40B",0,0,"keyless","liquid","unknown"),
        new("llm7","gpt-4o-mini-2024-07-18","GPT-4o mini (LLM7)",150000000,0,"recurring-daily","llm7-free","caution"),
        new("llm7","gpt-4.1-nano-2025-04-14","GPT-4.1 nano (LLM7)",0,0,"recurring-daily","llm7-free","caution"),
        new("llm7","deepseek-r1-0528","DeepSeek R1 (LLM7)",0,0,"recurring-daily","llm7-free","caution"),
        new("llm7","qwen2.5-coder-32b-instruct","Qwen2.5 Coder 32B (LLM7)",0,0,"recurring-daily","llm7-free","caution"),
        new("longcat","LongCat-2.0","LongCat-2.0",0,10000000,"one-time-initial","longcat-free","caution"),
        new("mistral","mistral-large-latest","Mistral Large 3",1000000000,0,"recurring-monthly","mistral","caution"),
        new("mistral","mistral-medium-3-5","Mistral Medium 3.5",1000000000,0,"recurring-monthly","mistral","caution"),
        new("mistral","mistral-small-latest","Mistral Small 4",1000000000,0,"recurring-monthly","mistral","caution"),
        new("mistral","devstral-latest","Devstral 2",1000000000,0,"recurring-monthly","mistral","caution"),
        new("mistral","codestral-latest","Codestral",1000000000,0,"recurring-monthly","mistral","caution"),
        new("monsterapi","llama-3-8b-fuse","Llama 3 8B Fuse",0,0,"one-time-initial","monsterapi","ambiguous"),
        new("morph","morph-v3-large","morph-v3-large",400000,0,"recurring-monthly","morph","ok"),
        new("morph","morph-v3-fast","morph-v3-fast",400000,0,"recurring-monthly","morph","ok"),
        new("muse-spark-web","muse-spark","Muse Spark",0,0,"keyless","muse-spark-web","avoid"),
        new("muse-spark-web","muse-spark-thinking","Muse Spark Thinking",0,0,"keyless","muse-spark-web","avoid"),
        new("muse-spark-web","muse-spark-contemplating","Muse Spark Contemplating",0,0,"keyless","muse-spark-web","avoid"),
        new("nebius","meta-llama/Llama-3.3-70B-Instruct","Llama 3.3 70B Instruct",0,1000000,"one-time-initial","nebius","caution"),
        new("nlpcloud","llama-3-8b-instruct","Llama 3 8B",0,0,"recurring-monthly","nlpcloud","avoid"),
        new("nous-research","Hermes-4-405B","Hermes 4 405B (Nous Research)",0,0,"recurring-credit","nous-research","ambiguous"),
        new("nous-research","Hermes-4-70B","Hermes 4 70B (Nous Research)",0,0,"recurring-credit","nous-research","ambiguous"),
        new("novita","ai-ai/llama-3.1-8b-instruct","Llama 3.1 8B",0,500000,"one-time-initial","novita","caution"),
        new("nscale","moonshotai/Kimi-K2.5","moonshotai/Kimi-K2.5",0,5000000,"one-time-initial","nscale","caution"),
        new("nscale","Qwen/Qwen3-235B-A22B-Instruct-2507","Qwen/Qwen3-235B-A22B-Instruct-2507",0,5000000,"one-time-initial","nscale","caution"),
        new("nscale","openai/gpt-oss-120b","openai/gpt-oss-120b",0,5000000,"one-time-initial","nscale","caution"),
        new("nscale","openai/gpt-oss-20b","openai/gpt-oss-20b",0,5000000,"one-time-initial","nscale","caution"),
        new("nscale","meta-llama/Llama-4-Scout-17B-16E-Instruct","meta-llama/Llama-4-Scout-17B-16E-Instruct",0,5000000,"one-time-initial","nscale","caution"),
        new("nscale","meta-llama/Llama-3.3-70B-Instruct","meta-llama/Llama-3.3-70B-Instruct",0,5000000,"one-time-initial","nscale","caution"),
        new("nvidia","google/gemma-4-31b-it","Gemma 4 31B",0,0,"one-time-initial","nvidia","caution"),
        new("nvidia","nvidia/nemotron-3-super-120b-a12b","Nemotron 3 Super 120B A12B",0,0,"one-time-initial","nvidia","caution"),
        new("nvidia","openai/gpt-oss-120b","GPT OSS 120B",0,0,"one-time-initial","nvidia","caution"),
        new("ollama-cloud","deepseek-v4-pro","DeepSeek V4 Pro",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","deepseek-v4-flash","DeepSeek V4 Flash",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","kimi-k2.6","Kimi K2.6",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","glm-5.1","GLM 5.1",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","minimax-m2.7","MiniMax M2.7",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","gemma4:31b","Gemma 4 31B",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","nemotron-3-super","NVIDIA Nemotron 3 Super",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("ollama-cloud","qwen3.5:397b","Qwen 3.5 397B",0,0,"recurring-uncapped","ollama-cloud","ambiguous"),
        new("opencode","big-pickle","Big Pickle",0,0,"keyless","opencode","avoid"),
        new("opencode","deepseek-v4-flash-free","DeepSeek V4 Flash Free",0,0,"keyless","opencode","avoid"),
        new("opencode","minimax-m2.5-free","MiniMax M2.5 Free",0,0,"keyless","opencode","avoid"),
        new("opencode","ling-2.6-1t-free","Ling 2.6 Free",0,0,"keyless","opencode","avoid"),
        new("opencode","trinity-large-preview-free","Trinity Large Preview Free",0,0,"keyless","opencode","avoid"),
        new("opencode","nemotron-3-super-free","Nemotron 3 Super Free",0,0,"keyless","opencode","avoid"),
        new("opencode","qwen3.6-plus-free","Qwen3.6 Plus Free",0,0,"keyless","opencode","avoid"),
        new("opencode-zen","opencode/big-pickle","Big Pickle (stealth)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("opencode-zen","opencode/deepseek-v4-flash-free","DeepSeek V4 Flash (free)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("opencode-zen","opencode/nemotron-3-super-free","Nemotron 3 Super (free)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("opencode-zen","opencode/mimo-v2.5-free","MiMo V2.5 (free)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("opencode-zen","opencode/north-mini-code-free","North Mini Code (free)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("opencode-zen","opencode/nemotron-3-ultra-free","Nemotron 3 Ultra (free)",0,0,"recurring-uncapped","opencode-zen-free","caution"),
        new("openrouter","auto","Auto (Best Available)",1200000,0,"recurring-daily","openrouter-free","caution"),
        new("openrouter","stealth/ox-alpha","Stealth Ox Alpha (free)",0,0,"recurring-daily","openrouter-free","caution"),
        new("openrouter","liquid/lfm-2.5-2.6b:free","LiquidAI: LFM2.5-2.6B (free)",0,0,"recurring-daily","openrouter-free","caution"),
        new("pollinations","openai","OpenAI (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","openai-fast","OpenAI Fast (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","openai-large","OpenAI Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","qwen-coder","Qwen Coder (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","mistral","Mistral (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","gemini-flash-lite-3.1","Gemini Flash Lite 3.1 (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","deepseek","DeepSeek (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","grok","Grok (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","grok-large","Grok Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","gemini-search","Gemini Search (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","perplexity-fast","Perplexity Fast (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","perplexity-reasoning","Perplexity Reasoning (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","kimi","Kimi (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","gemini-large","Gemini Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","nova-fast","Nova Fast (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","nova","Nova (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","glm","GLM (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","minimax","MiniMax (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","mistral-large","Mistral Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","polly","Polly (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","qwen-coder-large","Qwen Coder Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","qwen-large","Qwen Large (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","qwen-vision","Qwen Vision (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("pollinations","qwen-safety","Qwen Safety (Pollinations)",0,0,"keyless","pollinations","caution"),
        new("predibase","llama-3.3-70b","llama-3.3-70b",0,25000000,"one-time-initial","predibase","caution"),
        new("publicai","swiss-ai/apertus-70b-instruct","swiss-ai/apertus-70b-instruct",0,0,"one-time-initial","publicai","caution"),
        new("publicai","aisingapore/Qwen-SEA-LION-v4-32B-IT","aisingapore/Qwen-SEA-LION-v4-32B-IT",0,0,"one-time-initial","publicai","caution"),
        new("publicai","allenai/Olmo-3-32B-Think","allenai/Olmo-3-32B-Think",0,0,"one-time-initial","publicai","caution"),
        new("qoder","qwen3.8-max-preview","Qwen3.8-Max-Preview",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","qwen3.7-max","Qwen3.7-Max",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","qwen3.7-plus","Qwen3.7-Plus",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","kimi-k3","Kimi-K3",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","kimi-k2.7-code","Kimi-K2.7-Code",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","glm-5.2","GLM-5.2",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","deepseek-v4-pro","DeepSeek-V4-Pro",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","deepseek-v4-flash","DeepSeek-V4-Flash",0,1000000,"one-time-initial","qoder","caution"),
        new("qoder","minimax-m3","MiniMax-M3",0,1000000,"one-time-initial","qoder","caution"),
        new("reka","reka-flash-3","Reka Flash 3",0,0,"recurring-monthly","reka","caution"),
        new("reka","reka-edge-2603","Reka Edge 2603",0,0,"recurring-monthly","reka","caution"),
        new("sambanova","MiniMax-M2.7","MiniMax-M2.7",6000000,0,"recurring-daily","sambanova","caution"),
        new("sambanova","DeepSeek-V3.2","DeepSeek-V3.2",6000000,0,"recurring-daily","sambanova","caution"),
        new("sambanova","Llama-4-Maverick-17B-128E-Instruct","Llama-4-Maverick-17B-128E-Instruct",6000000,0,"recurring-daily","sambanova","caution"),
        new("sambanova","Meta-Llama-3.3-70B-Instruct","Meta-Llama-3.3-70B-Instruct",6000000,0,"recurring-daily","sambanova","caution"),
        new("sambanova","gpt-oss-120b","gpt-oss-120b",6000000,0,"recurring-daily","sambanova","caution"),
        new("scaleway","qwen3-235b-a22b-instruct-2507","Qwen3 235B A22B (1M free tok 🆓)",0,1000000,"one-time-initial","scaleway","ok"),
        new("scaleway","llama-3.1-70b-instruct","Llama 3.1 70B (🆓 EU)",0,1000000,"one-time-initial","scaleway","ok"),
        new("scaleway","llama-3.1-8b-instruct","Llama 3.1 8B (🆓 EU)",0,1000000,"one-time-initial","scaleway","ok"),
        new("scaleway","mistral-small-3.2-24b-instruct-2506","Mistral Small 3.2 (🆓 EU)",0,1000000,"one-time-initial","scaleway","ok"),
        new("scaleway","deepseek-v3-0324","DeepSeek V3 (🆓 EU)",0,1000000,"one-time-initial","scaleway","ok"),
        new("scaleway","gpt-oss-120b","GPT-OSS 120B (🆓 EU)",0,1000000,"one-time-initial","scaleway","ok"),
        new("sensenova","sensechat","SenseChat",0,0,"one-time-initial","sensenova","caution"),
        new("siliconflow","deepseek-ai/DeepSeek-V3.2","DeepSeek V3.2",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","deepseek-ai/DeepSeek-V3.1","DeepSeek V3.1",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","deepseek-ai/DeepSeek-R1","DeepSeek R1",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","Qwen/Qwen3-235B-A22B-Instruct-2507","Qwen3 235B",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","Qwen/Qwen3-Coder-480B-A35B-Instruct","Qwen3 Coder 480B",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","Qwen/Qwen3-32B","Qwen3 32B",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","moonshotai/Kimi-K2.5","Kimi K2.5",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","zai-org/GLM-4.7","GLM 4.7",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","openai/gpt-oss-120b","GPT OSS 120B",0,0,"recurring-uncapped","siliconflow","caution"),
        new("siliconflow","baidu/ERNIE-4.5-300B-A47B","ERNIE 4.5 300B",0,0,"recurring-uncapped","siliconflow","caution"),
        new("sparkdesk","lite","Spark Lite",0,0,"keyless","sparkdesk","caution"),
        new("stepfun","step-1v","Step 1V",0,0,"one-time-initial","stepfun","ok"),
        new("t3-web","claude-opus-4","Claude Opus 4 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","claude-sonnet-4","Claude Sonnet 4 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","claude-haiku-4","Claude Haiku 4 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","claude-3.7","Claude 3.7 Sonnet (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","gpt-5","GPT-5 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","gpt-4o","GPT-4o (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","gpt-4.1","GPT-4.1 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","o3","o3 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","o4-mini","o4-mini (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","gemini-2.5-pro","Gemini 2.5 Pro (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","gemini-2.5-flash","Gemini 2.5 Flash (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","deepseek-r1","DeepSeek R1 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","deepseek-v3","DeepSeek V3 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","grok-3","Grok 3 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","grok-3-mini","Grok 3 Mini (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","llama-4-maverick","Llama 4 Maverick (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","llama-4-scout","Llama 4 Scout (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","llama-3.3-70b","Llama 3.3 70B (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","devstral","Devstral (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","mistral-large","Mistral Large (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","qwen3-235b","Qwen3 235B (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","qwen3-32b","Qwen3 32B (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("t3-web","kimi-k2","Kimi K2 (via t3.chat)",0,0,"recurring-daily","t3-web","avoid"),
        new("tencent","hunyuan-pro","Hunyuan Pro",0,0,"recurring-uncapped","tencent","caution"),
        new("uncloseai","Lorbus/Qwen3.6-27B-int4-AutoRound","Qwen3.6 27B int4 AutoRound (🆓 Free)",0,0,"keyless","uncloseai","caution"),
        new("vertex","gemini-3.1-pro-preview","Gemini 3.1 Pro Preview (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3.1-flash-lite","Gemini 3.1 Flash Lite (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3-flash-preview","Gemini 3 Flash Preview (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3.7-flash","Gemini 3.7 Flash (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3.6-flash","Gemini 3.6 Flash (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3.5-flash","Gemini 3.5 Flash (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-3.5-flash-lite","Gemini 3.5 Flash-Lite (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-2.5-pro","Gemini 2.5 Pro (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-2.5-flash","Gemini 2.5 Flash (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","gemini-2.5-flash-lite","Gemini 2.5 Flash-Lite (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","deepseek-ai/deepseek-v3.2-maas","DeepSeek V3.2 (Vertex MaaS)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","deepseek-ai/deepseek-v3.1-maas","DeepSeek V3.1 (Vertex MaaS)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","qwen/qwen3-next-80b-a3b-instruct-maas","Qwen3 Next 80B Instruct (Vertex MaaS)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","zai-org/glm-5-maas","GLM 5 (Vertex MaaS)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","claude-opus-4-7","Claude Opus 4.7 (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("vertex","claude-sonnet-4-6","Claude Sonnet 4.6 (Vertex)",0,300000000,"one-time-initial","vertex","caution"),
        new("requesty","openai/gpt-oss-120b","GPT-OSS 120B (Requesty free)",0,0,"recurring-uncapped","requesty-free","ok"),
        new("requesty","mistral/leanstral-1-5","Leanstral 1.5 (Requesty free)",0,0,"recurring-uncapped","requesty-free","ok"),
        new("requesty","nvidia/nemotron-3-nano-30b-a3b","Nemotron 3 Nano 30B (Requesty free)",0,0,"recurring-uncapped","requesty-free","ok"),
        new("ovhcloud","gpt-oss-120b","GPT-OSS 120B (OVH anonymous)",0,0,"keyless","ovhcloud-anon","ok"),
        new("ovhcloud","gpt-oss-20b","GPT-OSS 20B (OVH anonymous)",0,0,"keyless","ovhcloud-anon","ok"),
        new("ovhcloud","Qwen3.6-27B","Qwen3.6 27B (OVH anonymous)",0,0,"keyless","ovhcloud-anon","ok"),
        new("ovhcloud","Mistral-Small-3.2-24B-Instruct-2506","Mistral Small 3.2 24B (OVH anonymous)",0,0,"keyless","ovhcloud-anon","ok"),
        new("ovhcloud","Qwen2.5-VL-72B-Instruct","Qwen2.5 VL 72B (OVH anonymous)",0,0,"keyless","ovhcloud-anon","ok"),
        new("agnes","agnes-2.0-flash","Agnes 2.0 Flash",0,0,"recurring-uncapped","agnes-free","ok"),
        new("agnes","agnes-2.5-flash","Agnes 2.5 Flash",0,0,"recurring-uncapped","agnes-free","ok"),
        new("agnes","agnes-3.0-flash","Agnes 3.0 Flash",0,0,"recurring-uncapped","agnes-free","ok"),
        new("agnes-cn","agnes-2.0-flash","Agnes 2.0 Flash",0,0,"recurring-uncapped","agnes-cn-free","ok"),
        new("agnes-cn","agnes-2.5-flash","Agnes 2.5 Flash",0,0,"recurring-uncapped","agnes-cn-free","ok"),
        new("agnes-cn","agnes-3.0-flash","Agnes 3.0 Flash",0,0,"recurring-uncapped","agnes-cn-free","ok"),
        new("glm","glm-4.7-flash","GLM-4.7-Flash",0,0,"recurring-uncapped","zhipu-flash-free","ok"),
        new("glm","glm-4.5-flash","GLM-4.5-Flash",0,0,"recurring-uncapped","zhipu-flash-free","ok"),
        new("navy","shared-pool","NavyAI free pool (150K tokens/day, shared)",4500000,0,"recurring-daily","navy-free","ok"),
        new("aihorde","aphrodite/TheDrummer/Cydonia-24B-v4.3","Cydonia 24B (AI Horde)",0,0,"keyless","aihorde-anon","ok"),
        new("aihorde","aphrodite/TheDrummer/Skyfall-31B-v4.2","Skyfall 31B (AI Horde)",0,0,"keyless","aihorde-anon","ok"),
        new("aihorde","google/gemma-4-31b","Gemma 4 31B (AI Horde)",0,0,"keyless","aihorde-anon","ok"),
        new("ainative","qwen3-235b-cerebras","Qwen3 235B (Cerebras)",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","qwen3-32b","Qwen3 32B",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","qwen3-14b","Qwen3 14B",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","qwen3-8b","Qwen3 8B",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","llama-4-maverick","Llama 4 Maverick",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","llama3.1-8b-cerebras","Llama 3.1 8B (Cerebras)",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","deepseek-r1","DeepSeek R1",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","nous-coder","Nous Coder",0,0,"recurring-uncapped","ainative-free","caution"),
        new("ainative","gemini-flash","Gemini Flash",0,0,"recurring-uncapped","ainative-free","caution"),
        new("aion","aion-labs/aion-3.0","Aion 3.0",0,0,"recurring-uncapped","aion-free","ok"),
        new("aion","aion-labs/aion-3.0-mini","Aion 3.0 Mini",0,0,"recurring-uncapped","aion-free","ok"),
        new("aion","aion-labs/aion-2.5","Aion 2.5",0,0,"recurring-uncapped","aion-free","ok"),
        new("aion","aion-labs/aion-2.0","Aion 2.0",0,0,"recurring-uncapped","aion-free","ok"),
        new("aion","aion-labs/aion-rp-llama-3.1-8b","Aion RP Llama 3.1 8B",0,0,"recurring-uncapped","aion-free","ok"),
        new("sealion","aisingapore/Llama-SEA-LION-v3.5-70B-R","Llama SEA-LION v3.5 70B R",0,0,"recurring-uncapped","sealion-free","ok"),
        new("sealion","aisingapore/Llama-SEA-LION-v3-70B-IT","Llama SEA-LION v3 70B IT",0,0,"recurring-uncapped","sealion-free","ok"),
        new("sealion","aisingapore/Gemma-SEA-LION-v4-27B-IT","Gemma SEA-LION v4 27B IT",0,0,"recurring-uncapped","sealion-free","ok"),
        new("sealion","aisingapore/Qwen-SEA-LION-v4.5-27B-IT","Qwen SEA-LION v4.5 27B IT",0,0,"recurring-uncapped","sealion-free","ok"),
        new("sealion","aisingapore/Qwen-SEA-LION-v4-32B-IT","Qwen SEA-LION v4 32B IT",0,0,"recurring-uncapped","sealion-free","ok"),
        new("routeway","llama-3.3-70b-instruct:free","Llama 3.3 70B Instruct (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","nemotron-3-nano-30b-a3b:free","Nemotron 3 Nano 30B (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","nemotron-nano-9b-v2:free","Nemotron Nano 9B v2 (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","step-3.7-flash:free","Step 3.7 Flash (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","step-3.5-flash:free","Step 3.5 Flash (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","laguna-m.1:free","Laguna M.1 (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","laguna-xs.2:free","Laguna XS.2 (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("routeway","llama-3.2-3b-instruct:free","Llama 3.2 3B Instruct (free)",0,0,"recurring-uncapped","routeway-free","caution"),
        new("nara","agnes-2.0-flash","Agnes 2.0 Flash",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","agnes-2.5-flash","Agnes 2.5 Flash",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","laguna-s-2.1","Laguna S 2.1",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","minimax-m3-free","MiniMax M3 Free",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","mistral-large","Mistral Large",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","mistral-medium-3-5","Mistral Medium 3.5",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","qwen3.8-27b","Qwen3.8 27B",210000000,0,"recurring-daily","nara-free","caution"),
        new("nara","stepfun-3.7-flash","StepFun 3.7 Flash",210000000,0,"recurring-daily","nara-free","caution"),
    ];
}
